openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations with contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-2xda.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/users/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/users/logout.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/users/register.yaml
  /auth/refresh-session:
    post:
      $ref: ../swagger/paths/users/refreshUsersSession.yaml
  /auth/request-reset:
    post:
      $ref: ../swagger/paths/users/requestResetToken.yaml
  /auth/reset-password:
    post:
      $ref: ../swagger/paths/users/resetPassword.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
